### ISSUE TITLE
Broken on vscode 1.36

### ISSUE THREAD

**Issue by benwinding** [manoj-makkuboy/vs-code-hacker-news#4]
Great idea, but is broken on the latest VScode
```
Version: 1.36.1
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:55:08.091Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-23-generic
```

**Comment by ekarbe** [comment]
Have you tried reloading VSCode? For me it worked after that.
But it's just a html view of the hackernews homepage, so not really worth it

**Comment by benwinding** [comment]
Hey @ekarbe,
Thanks, yeah that worked, but yeah I can't interact with the site much or login, just links to other pages. Could be worth an updating though.
Cheers,
Ben
